name: Deploy Automático

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Disparar webhook n8n
        run: |
          curl -X POST  https://www.retrogamesonline.com.br/webhook/deploy \
          -H "Content-Type: application/json" \
          -d '{"status":"deploy iniciado"}'